# Generated by Django 6.0.4 on 2026-04-28 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_testimonial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='module',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_modules', to='lms.batch'),
        ),
        migrations.AddField(
            model_name='module',
            name='duration_weeks',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CourseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/requirements/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('topic_title', models.CharField(max_length=255)),
                ('quiz_count', models.IntegerField(default=0)),
                ('assignment_count', models.IntegerField(default=0)),
                ('is_disabled', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='lms.module')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('topics', models.TextField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='lms.moduleweek')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lms.moduleweek'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='courses/projects/')),
                ('description', models.TextField()),
                ('tools_images', models.JSONField(default=list, help_text='List of tool image URLs or references')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_projects', to='lms.course')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectToolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/projects/tools/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools_images_list', to='lms.project')),
            ],
        ),
        migrations.CreateModel(
            name='ToolTech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='courses/tools/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='lms.course')),
            ],
        ),
    ]
