# Generated by Django 6.0.4 on 2026-04-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_rename_title_module_name_module_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='class_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='schedule_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_seats',
            field=models.IntegerField(default=0),
        ),
    ]
