# Generated by Django 6.0.4 on 2026-04-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_course_batch_no_course_class_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('live', 'Live'), ('pre_recorded', 'Pre-Recorded')], default='live', max_length=20),
        ),
    ]
