# Generated by Django 6.0.4 on 2026-04-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seats_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='support_class_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
