# Generated by Django 6.0.4 on 2026-05-01 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_module_instructor_moduleweek_extra_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_modules', to='lms.batch'),
        ),
    ]
