# Generated by Django 6.0.4 on 2026-05-02 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_alter_module_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='seats_left',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_seats',
        ),
    ]
