# Generated by Django 6.0.4 on 2026-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_remove_course_seats_left_remove_course_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_seats',
            field=models.IntegerField(default=50),
        ),
    ]
