# Generated by Django 6.0.4 on 2026-05-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_course_is_published_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/projects/'),
        ),
        migrations.AlterField(
            model_name='projecttoolimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/projects/tools/'),
        ),
        migrations.AlterField(
            model_name='tooltech',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/tools/'),
        ),
    ]
