# Generated by Django 6.0.4 on 2026-05-24 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_alter_project_image_alter_projecttoolimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('total_marks', models.IntegerField(default=100)),
                ('allow_late_submission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField(blank=True, null=True)),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('passing_score', models.IntegerField(default=50)),
                ('auto_evaluation', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_avg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moduleweek',
            name='duration_days',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='moduleweek',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moduleweek',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, null=True)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='assignments/submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marks_obtained', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text="List of options, e.g. ['A', 'B', 'C', 'D']")),
                ('correct_answer', models.CharField(help_text='Correct option. Hidden from API until close_time.', max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(help_text='Student answers mapping question ID to selected option')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeekItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('live_class', 'Live Class'), ('assignment', 'Assignment'), ('quiz', 'Quiz'), ('project', 'Project'), ('resource', 'Resource')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible payload for type-specific data (e.g. meeting_link for live_class)')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms.moduleweek')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='week_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_details', to='lms.weekitem'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='week_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_details', to='lms.weekitem'),
        ),
    ]
