# Generated by Django 6.0.4 on 2026-04-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_guestuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='LMS Platform', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('footer_description', models.TextField(default="Bangladesh's premier live-learning platform. Master high-demand tech skills with industry experts.")),
                ('contact_email', models.EmailField(default='support@lmsplatform.com', max_length=254)),
                ('contact_address', models.TextField(default='Ka-6/a, Navana Sylvania, Baridhara Road, Nadda, Gulshan-2, Dhaka-1212')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('instructor', 'Instructor'), ('support_instructor', 'Support Instructor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
