# Generated by Django 6.0.4 on 2026-04-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_sitesettings_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© 2026 LMS Platform. All Rights Reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='website_title',
            field=models.CharField(default='LMS Platform - Learn Skills Live', max_length=200),
        ),
    ]
