# Generated by Django 6.0.4 on 2026-04-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_sitesettings_copyright_text_sitesettings_favicon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/icons/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/icons/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/icons/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/icons/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube_icon',
            field=models.ImageField(blank=True, null=True, upload_to='site/icons/'),
        ),
    ]
