# Generated by Django 6.0.4 on 2026-04-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_sitesettings_facebook_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id_custom',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='© {year} LMS Platform. All Rights Reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('moderator', 'Moderator'), ('instructor', 'Instructor'), ('teaching_assistant', 'Teaching Assistant'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
