# Generated by Django 6.0.4 on 2026-04-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_mobile_number_user_user_id_custom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profession',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alternative_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alternative_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_background',
            field=models.CharField(blank=True, choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('Diploma', 'Diploma'), ('HSC', 'HSC'), ('SSC', 'SSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BSS', 'BSS'), ('MSS', 'MSS'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('LLB', 'LLB'), ('LLM', 'LLM'), ('PhD', 'PhD'), ('MPhil', 'MPhil'), ('Vocational', 'Vocational Training'), ('Professional', 'Professional Certification'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='edu_institute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill_sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
