# Generated by Django 6.0.4 on 2026-04-30 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_from_date_profile_is_continuing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='to_date',
        ),
    ]
