# Generated by Django 6.0.4 on 2026-05-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_date_of_birth_profile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edu_background',
            field=models.CharField(blank=True, choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('Diploma', 'Diploma'), ('HSC', 'HSC'), ('SSC', 'SSC'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('BA', 'BA'), ('MA', 'MA'), ('BSS', 'BSS'), ('MSS', 'MSS'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('LLB', 'LLB'), ('LLM', 'LLM'), ('PhD', 'PhD'), ('MPhil', 'MPhil'), ('Vocational', 'Vocational Training'), ('Professional', 'Professional Certification'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.CharField(blank=True, help_text='Company Name', max_length=255, null=True),
        ),
    ]
