# Generated by Django 6.0.4 on 2026-05-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_actionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_badge_text',
            field=models.CharField(default='# Online Learning Platform in Bangladesh', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading',
            field=models.CharField(default='Skills that Launch Your Career.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_highlighted_word',
            field=models.CharField(blank=True, default='Launch', help_text='Word in the heading to highlight', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subheading',
            field=models.TextField(default='Join thousands of students mastering high-demand skills through live mentorship and industry-grade projects.'),
        ),
        migrations.DeleteModel(
            name='ActionLog',
        ),
    ]
